version: '3.8'

services:
  # TensorFlow Serving for Potato Disease Detection
  tensorflow-serving:
    image: tensorflow/serving:latest
    container_name: potato-disease-tf-serving
    ports:
      - "8501:8501"  # REST API port
      - "8500:8500"  # gRPC API port (optional)
    volumes:
      # Mount the models directory to the container
      - ./models:/models
    environment:
      # Model configuration
      - MODEL_NAME=potato_model
      - MODEL_BASE_PATH=/models
    command: >
      --rest_api_port=8501
      --model_config_file_poll_wait_seconds=60
      --allow_version_labels_for_unavailable_models=true
      --rest_api_timeout_in_ms=30000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/v1/models/potato_model"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tf-serving-network

networks:
  tf-serving-network:
    driver: bridge